# Generated by Django 2.2.3 on 2019-07-28 11:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_id', models.BigIntegerField()),
                ('citizen_id', models.BigIntegerField()),
                ('town', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255)),
                ('appartement', models.CharField(max_length=255)),
                ('birth_date', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('relatives', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, size=None)),
            ],
            options={
                'unique_together': {('import_id', 'citizen_id')},
            },
        ),
    ]
