# Generated by Django 2.2.3 on 2019-07-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='name',
            field=models.CharField(default='adsd', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citizen',
            name='appartement',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='gender',
            field=models.CharField(max_length=6),
        ),
    ]
