# Generated by Django 2.2.3 on 2019-07-31 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20190728_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='appartement',
            new_name='apartment',
        ),
    ]
