# Generated by Django 2.2.3 on 2019-08-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_citizen_appartement_renamed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
